CREATE TABLE people (
    playerID VARCHAR(20) NOT NULL,
    birthYear SMALLINT NULL,
    birthMonth TINYINT NULL,
    birthDay TINYINT NULL,
    birthCountry VARCHAR(100) NULL,
    birthState VARCHAR(100) NULL,
    birthCity VARCHAR(100) NULL,
    deathYear SMALLINT NULL,
    deathMonth TINYINT NULL,
    deathDay TINYINT NULL,
    deathCountry VARCHAR(100) NULL,
    deathState VARCHAR(100) NULL,
    deathCity VARCHAR(100) NULL,
    nameFirst VARCHAR(100) NULL,
    nameLast VARCHAR(100) NULL,
    nameGiven VARCHAR(150) NULL,
    weight SMALLINT NULL,
    height SMALLINT NULL,
    bats CHAR(1) NULL,
    throws CHAR(1) NULL,
    debut DATE NULL,
    finalGame DATE NULL,
    retroID VARCHAR(20) NULL,
    bbrefID VARCHAR(20) NULL,
    PRIMARY KEY (playerID)
);