// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Merchant struct {
	ID                   int32          `json:"id"`
	Name                 string         `json:"name"`
	Email                string         `json:"email"`
	Password             string         `json:"password"`
	Phone                string         `json:"phone"`
	CommissionPercentage sql.NullString `json:"commission_percentage"`
	CreatedAt            sql.NullTime   `json:"created_at"`
}
