// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO customers (
    name,
    email,
    password,
    payment_due_date
)
VALUES (
    ?,
    ?,
    ?,
    ?
)
`

type CreateCustomerParams struct {
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	Password       string    `json:"password"`
	PaymentDueDate time.Time `json:"payment_due_date"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PaymentDueDate,
	)
}

const decreaseCustomerDue = `-- name: DecreaseCustomerDue :exec
UPDATE customers
SET total_due = total_due - ?
WHERE id = ?
`

type DecreaseCustomerDueParams struct {
	TotalDue sql.NullString `json:"total_due"`
	ID       int32          `json:"id"`
}

func (q *Queries) DecreaseCustomerDue(ctx context.Context, arg DecreaseCustomerDueParams) error {
	_, err := q.db.ExecContext(ctx, decreaseCustomerDue, arg.TotalDue, arg.ID)
	return err
}

const deleteCustomerById = `-- name: DeleteCustomerById :exec
DELETE
FROM customers
WHERE id = ?
`

func (q *Queries) DeleteCustomerById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerById, id)
	return err
}

const getAllCustomers = `-- name: GetAllCustomers :many
SELECT id, name, email, password, credit_limit, total_due, payment_due_date, status, created_at 
FROM customers
`

func (q *Queries) GetAllCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.CreditLimit,
			&i.TotalDue,
			&i.PaymentDueDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, name, email, password, credit_limit, total_due, payment_due_date, status, created_at
FROM customers
WHERE email = ?
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreditLimit,
		&i.TotalDue,
		&i.PaymentDueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, email, password, credit_limit, total_due, payment_due_date, status, created_at
FROM customers
WHERE id = ?
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreditLimit,
		&i.TotalDue,
		&i.PaymentDueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByIDForUpdate = `-- name: GetCustomerByIDForUpdate :one
SELECT id, name, email, password, credit_limit, total_due, payment_due_date, status, created_at
FROM customers
WHERE id = ?
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetCustomerByIDForUpdate(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByIDForUpdate, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreditLimit,
		&i.TotalDue,
		&i.PaymentDueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerDueByName = `-- name: GetCustomerDueByName :one
SELECT id, name, email, password, credit_limit, total_due, payment_due_date, status, created_at
FROM customers
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetCustomerDueByName(ctx context.Context, name string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerDueByName, name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreditLimit,
		&i.TotalDue,
		&i.PaymentDueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomersWithDue = `-- name: GetCustomersWithDue :many
SELECT id, name, email, password, credit_limit, total_due, payment_due_date, status, created_at
FROM customers
WHERE total_due > 0
ORDER BY total_due DESC
`

func (q *Queries) GetCustomersWithDue(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getCustomersWithDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.CreditLimit,
			&i.TotalDue,
			&i.PaymentDueDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersAtCreditLimit = `-- name: GetUsersAtCreditLimit :many
SELECT id, name, email, password, credit_limit, total_due, payment_due_date, status, created_at
FROM customers
WHERE total_due >= credit_limit
`

func (q *Queries) GetUsersAtCreditLimit(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getUsersAtCreditLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.CreditLimit,
			&i.TotalDue,
			&i.PaymentDueDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseCustomerDue = `-- name: IncreaseCustomerDue :exec
UPDATE customers
SET total_due = total_due + ?
WHERE id = ?
`

type IncreaseCustomerDueParams struct {
	TotalDue sql.NullString `json:"total_due"`
	ID       int32          `json:"id"`
}

func (q *Queries) IncreaseCustomerDue(ctx context.Context, arg IncreaseCustomerDueParams) error {
	_, err := q.db.ExecContext(ctx, increaseCustomerDue, arg.TotalDue, arg.ID)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET
    name = ?,
    email = ?
WHERE id = ?
`

type UpdateCustomerParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer, arg.Name, arg.Email, arg.ID)
	return err
}

const updateCustomerDue = `-- name: UpdateCustomerDue :exec
UPDATE customers
SET total_due = ?
WHERE id = ?
`

type UpdateCustomerDueParams struct {
	TotalDue sql.NullString `json:"total_due"`
	ID       int32          `json:"id"`
}

func (q *Queries) UpdateCustomerDue(ctx context.Context, arg UpdateCustomerDueParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerDue, arg.TotalDue, arg.ID)
	return err
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :exec
UPDATE customers
SET status = ?
WHERE id = ?
`

type UpdateCustomerStatusParams struct {
	Status NullCustomersStatus `json:"status"`
	ID     int32               `json:"id"`
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerStatus, arg.Status, arg.ID)
	return err
}
