// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CustomersStatus string

const (
	CustomersStatusACTIVE  CustomersStatus = "ACTIVE"
	CustomersStatusBLOCKED CustomersStatus = "BLOCKED"
)

func (e *CustomersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomersStatus(s)
	case string:
		*e = CustomersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomersStatus: %T", src)
	}
	return nil
}

type NullCustomersStatus struct {
	CustomersStatus CustomersStatus `json:"customers_status"`
	Valid           bool            `json:"valid"`
}

func (ns *NullCustomersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CustomersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomersStatus.Scan(value)
}

func (ns NullCustomersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomersStatus), nil
}

type Customer struct {
	ID             int32               `json:"id"`
	Name           string              `json:"name"`
	Email          string              `json:"email"`
	Password       string              `json:"password"`
	CreditLimit    string              `json:"credit_limit"`
	TotalDue       sql.NullString      `json:"total_due"`
	PaymentDueDate time.Time           `json:"payment_due_date"`
	Status         NullCustomersStatus `json:"status"`
	CreatedAt      sql.NullTime        `json:"created_at"`
}
