apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: paylater
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

      # it just telling mysql to use 2gb of persistent storage - so storage remain in pvc but wont erase if pod dies