apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant
  namespace: paylater

spec:
  replicas: 1

  selector:
    matchLabels:
      app: merchant

  template:
    metadata:
      labels:
        app: merchant

    spec:
      containers:
        - name: merchant
          image: tejanamburi13/paylater-merchant:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 9092

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_PORT

            - name: DB_NAME
              value: "merchant_db"

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paylater-secret
                  key: MYSQL_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paylater-secret
                  key: JWT_SECRET

            - name: JWT_EXPIRY
              value: "24h"

            - name: PORT
              value: "9092"

            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: paylater-secret
                  key: INTERNAL_SERVICE_TOKEN