apiVersion: v1
kind: Service
metadata:
  name: merchant
  namespace: paylater

spec:
  selector:
    app: merchant

  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

  type: ClusterIP