apiVersion: v1
kind: ConfigMap
metadata:
  name: paylater-config
  namespace: paylater

data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: go_user

  JWT_EXPIRY: "24h"

  ADMIN_SERVICE_URL: "http://admin:9091"
  CUSTOMER_SERVICE_URL: "http://customer:9093"
  MERCHANT_SERVICE_URL: "http://merchant:9092"
  LEDGER_SERVICE_URL: "http://ledger:9094"
  REPORT_SERVICE_URL: "http://report:9095"

  CORS_ALLOWED_ORIGINS: "http://localhost:5173"