apiVersion: v1
kind: Secret
metadata:
  name: paylater-secret
  namespace: paylater
type: Opaque

stringData:
  JWT_SECRET: "paylater-super-secret-key"
  INTERNAL_SERVICE_TOKEN: "paylater-internal-dev-token"
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_PASSWORD: "go123"