apiVersion: apps/v1
kind: Deployment

metadata:
  name: customer
  namespace: paylater

spec:
  replicas: 1

  selector:
    matchLabels:
      app: customer

  template:
    metadata:
      labels:
        app: customer

    spec:
      containers:
        - name: customer
          image: tejanamburi13/paylater-customer:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 9093

          startupProbe:
            httpGet:
              path: /health
              port: 9093
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /health
              port: 9093
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 9093
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_PORT

            - name: DB_NAME
              value: "customer_db"

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paylater-secret
                  key: MYSQL_PASSWORD

            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: paylater-secret
                  key: INTERNAL_SERVICE_TOKEN

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paylater-secret
                  key: JWT_SECRET

            - name: JWT_EXPIRY
              value: "24h"

            - name: PORT
              value: "9093"