// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type TransactionsTransactionType string

const (
	TransactionsTransactionTypePURCHASE TransactionsTransactionType = "PURCHASE"
	TransactionsTransactionTypePAYBACK  TransactionsTransactionType = "PAYBACK"
)

func (e *TransactionsTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsTransactionType(s)
	case string:
		*e = TransactionsTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsTransactionType: %T", src)
	}
	return nil
}

type NullTransactionsTransactionType struct {
	TransactionsTransactionType TransactionsTransactionType `json:"transactions_transaction_type"`
	Valid                       bool                        `json:"valid"`
}

func (ns *NullTransactionsTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsTransactionType.Scan(value)
}

func (ns NullTransactionsTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsTransactionType), nil
}

type Transaction struct {
	ID                   int32                       `json:"id"`
	CustomerID           int32                       `json:"customer_id"`
	MerchantID           sql.NullInt32               `json:"merchant_id"`
	TransactionType      TransactionsTransactionType `json:"transaction_type"`
	Amount               string                      `json:"amount"`
	CommissionPercentage sql.NullString              `json:"commission_percentage"`
	CommissionAmount     sql.NullString              `json:"commission_amount"`
	TransactionDate      sql.NullTime                `json:"transaction_date"`
}
