apiVersion: v1
kind: Service

metadata:
  name: ledger
  namespace: paylater

spec:
  selector:
    app: ledger

  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094

  type: ClusterIP