// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO customers (
    name,
    email
)
VALUES (
    ?,
    ?
)
`

type CreateCustomerParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer, arg.Name, arg.Email)
}

const deleteCustomerById = `-- name: DeleteCustomerById :exec
DELETE
FROM customers
WHERE id = ?
`

func (q *Queries) DeleteCustomerById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerById, id)
	return err
}

const getAllCustomers = `-- name: GetAllCustomers :many
SELECT id, name, email, credit_limit, total_due, created_at 
FROM customers
`

func (q *Queries) GetAllCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreditLimit,
			&i.TotalDue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, email, credit_limit, total_due, created_at
FROM customers
WHERE id = ?
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreditLimit,
		&i.TotalDue,
		&i.CreatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET
    name = ?,
    email = ?
WHERE id = ?
`

type UpdateCustomerParams struct {
	Name  string
	Email string
	ID    int32
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer, arg.Name, arg.Email, arg.ID)
	return err
}

const updateCustomerDue = `-- name: UpdateCustomerDue :exec
UPDATE customers
SET total_due = ?
WHERE id = ?
`

type UpdateCustomerDueParams struct {
	TotalDue sql.NullString
	ID       int32
}

func (q *Queries) UpdateCustomerDue(ctx context.Context, arg UpdateCustomerDueParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerDue, arg.TotalDue, arg.ID)
	return err
}
