// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"
	"database/sql"
)

const createMerchant = `-- name: CreateMerchant :execresult
INSERT INTO merchants (
    name,
    email,
    phone,
    commission_percentage
)
VALUES (
    ?,
    ?,
    ?,
    ?
)
`

type CreateMerchantParams struct {
	Name                 string
	Email                string
	Phone                sql.NullString
	CommissionPercentage string
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.CommissionPercentage,
	)
}

const getAllMerchants = `-- name: GetAllMerchants :many
SELECT id, name, email, phone, commission_percentage
FROM merchants
`

func (q *Queries) GetAllMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.QueryContext(ctx, getAllMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, name, email, phone, commission_percentage
FROM merchants
WHERE id = ?
`

func (q *Queries) GetMerchantByID(ctx context.Context, id int32) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.CommissionPercentage,
	)
	return i, err
}

const updateMerchantCommission = `-- name: UpdateMerchantCommission :exec
UPDATE merchants
SET commission_percentage = ?
WHERE id = ?
`

type UpdateMerchantCommissionParams struct {
	CommissionPercentage string
	ID                   int32
}

func (q *Queries) UpdateMerchantCommission(ctx context.Context, arg UpdateMerchantCommissionParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchantCommission, arg.CommissionPercentage, arg.ID)
	return err
}
