// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"
	"database/sql"
)

const createMerchant = `-- name: CreateMerchant :execresult
INSERT INTO merchants (
    name,
    email,
    password,
    phone,
    commission_percentage
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateMerchantParams struct {
	Name                 string `json:"name"`
	Email                string `json:"email"`
	Password             string `json:"password"`
	Phone                string `json:"phone"`
	CommissionPercentage string `json:"commission_percentage"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.CommissionPercentage,
	)
}

const deleteMerchantById = `-- name: DeleteMerchantById :exec
DELETE
FROM merchants
WHERE id = ?
`

func (q *Queries) DeleteMerchantById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMerchantById, id)
	return err
}

const getAllMerchants = `-- name: GetAllMerchants :many
SELECT id, name, email, password, phone, commission_percentage, created_at
FROM merchants
`

func (q *Queries) GetAllMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.QueryContext(ctx, getAllMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.CommissionPercentage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT id, name, email, password, phone, commission_percentage, created_at
FROM merchants
WHERE email = ?
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, email string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByEmail, email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.CommissionPercentage,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, name, email, password, phone, commission_percentage, created_at
FROM merchants
WHERE id = ?
`

func (q *Queries) GetMerchantByID(ctx context.Context, id int32) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.CommissionPercentage,
		&i.CreatedAt,
	)
	return i, err
}

const updateMerchant = `-- name: UpdateMerchant :exec
UPDATE merchants
SET name = ?,email = ?
WHERE id = ?
`

type UpdateMerchantParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchant, arg.Name, arg.Email, arg.ID)
	return err
}

const updateMerchantCommission = `-- name: UpdateMerchantCommission :exec
UPDATE merchants
SET commission_percentage = ?
WHERE id = ?
`

type UpdateMerchantCommissionParams struct {
	CommissionPercentage string `json:"commission_percentage"`
	ID                   int32  `json:"id"`
}

func (q *Queries) UpdateMerchantCommission(ctx context.Context, arg UpdateMerchantCommissionParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchantCommission, arg.CommissionPercentage, arg.ID)
	return err
}
