// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type TransactionsTransactionType string

const (
	TransactionsTransactionTypePURCHASE TransactionsTransactionType = "PURCHASE"
	TransactionsTransactionTypePAYBACK  TransactionsTransactionType = "PAYBACK"
)

func (e *TransactionsTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsTransactionType(s)
	case string:
		*e = TransactionsTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsTransactionType: %T", src)
	}
	return nil
}

type NullTransactionsTransactionType struct {
	TransactionsTransactionType TransactionsTransactionType
	Valid                       bool // Valid is true if TransactionsTransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsTransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsTransactionType), nil
}

type Customer struct {
	ID          int32
	Name        string
	Email       string
	CreditLimit string
	TotalDue    sql.NullString
	CreatedAt   sql.NullTime
}

type Merchant struct {
	ID                   int32
	Name                 string
	Email                string
	Phone                sql.NullString
	CommissionPercentage string
}

type Transaction struct {
	ID                   int32
	CustomerID           int32
	MerchantID           sql.NullInt32
	TransactionType      TransactionsTransactionType
	Amount               string
	CommissionPercentage sql.NullString
	CommissionAmount     sql.NullString
	TransactionDate      sql.NullTime
}
