// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type CustomersStatus string

const (
	CustomersStatusACTIVE  CustomersStatus = "ACTIVE"
	CustomersStatusBLOCKED CustomersStatus = "BLOCKED"
)

func (e *CustomersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomersStatus(s)
	case string:
		*e = CustomersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomersStatus: %T", src)
	}
	return nil
}

type NullCustomersStatus struct {
	CustomersStatus CustomersStatus `json:"customers_status"`
	Valid           bool            `json:"valid"` // Valid is true if CustomersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CustomersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomersStatus), nil
}

type TransactionsTransactionType string

const (
	TransactionsTransactionTypePURCHASE TransactionsTransactionType = "PURCHASE"
	TransactionsTransactionTypePAYBACK  TransactionsTransactionType = "PAYBACK"
)

func (e *TransactionsTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsTransactionType(s)
	case string:
		*e = TransactionsTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsTransactionType: %T", src)
	}
	return nil
}

type NullTransactionsTransactionType struct {
	TransactionsTransactionType TransactionsTransactionType `json:"transactions_transaction_type"`
	Valid                       bool                        `json:"valid"` // Valid is true if TransactionsTransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsTransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsTransactionType), nil
}

type Admin struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Customer struct {
	ID             int32               `json:"id"`
	Name           string              `json:"name"`
	Email          string              `json:"email"`
	Password       string              `json:"password"`
	CreditLimit    string              `json:"credit_limit"`
	TotalDue       sql.NullString      `json:"total_due"`
	PaymentDueDate sql.NullTime        `json:"payment_due_date"`
	Status         NullCustomersStatus `json:"status"`
	CreatedAt      sql.NullTime        `json:"created_at"`
}

type Merchant struct {
	ID                   int32        `json:"id"`
	Name                 string       `json:"name"`
	Email                string       `json:"email"`
	Password             string       `json:"password"`
	Phone                string       `json:"phone"`
	CommissionPercentage string       `json:"commission_percentage"`
	CreatedAt            sql.NullTime `json:"created_at"`
}

type Transaction struct {
	ID                   int32                       `json:"id"`
	CustomerID           int32                       `json:"customer_id"`
	MerchantID           sql.NullInt32               `json:"merchant_id"`
	TransactionType      TransactionsTransactionType `json:"transaction_type"`
	Amount               string                      `json:"amount"`
	CommissionPercentage sql.NullString              `json:"commission_percentage"`
	CommissionAmount     sql.NullString              `json:"commission_amount"`
	TransactionDate      sql.NullTime                `json:"transaction_date"`
}
