// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"database/sql"
)

const getAllMerchantsFeeCollected = `-- name: GetAllMerchantsFeeCollected :many
SELECT
    m.id,
    m.name,
    COALESCE(SUM(t.commission_amount), 0) AS total_fee_collected
FROM merchants m
LEFT JOIN transactions t
    ON m.id = t.merchant_id
GROUP BY m.id, m.name
ORDER BY total_fee_collected DESC
`

type GetAllMerchantsFeeCollectedRow struct {
	ID                int32       `json:"id"`
	Name              string      `json:"name"`
	TotalFeeCollected interface{} `json:"total_fee_collected"`
}

func (q *Queries) GetAllMerchantsFeeCollected(ctx context.Context) ([]GetAllMerchantsFeeCollectedRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMerchantsFeeCollected)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMerchantsFeeCollectedRow
	for rows.Next() {
		var i GetAllMerchantsFeeCollectedRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TotalFeeCollected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerDueByName = `-- name: GetCustomerDueByName :many
SELECT total_due
FROM customers
WHERE name = ?
`

func (q *Queries) GetCustomerDueByName(ctx context.Context, name string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerDueByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var total_due sql.NullString
		if err := rows.Scan(&total_due); err != nil {
			return nil, err
		}
		items = append(items, total_due)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomersWithDue = `-- name: GetCustomersWithDue :many
SELECT id, name, email, credit_limit, total_due, created_at
FROM customers
WHERE total_due > 0
ORDER BY total_due DESC
`

func (q *Queries) GetCustomersWithDue(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getCustomersWithDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreditLimit,
			&i.TotalDue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersAtCreditLimit = `-- name: GetUsersAtCreditLimit :many
SELECT id, name, email, credit_limit, total_due, created_at
FROM customers
WHERE total_due = credit_limit
`

func (q *Queries) GetUsersAtCreditLimit(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getUsersAtCreditLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreditLimit,
			&i.TotalDue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
