// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :execresult
INSERT INTO transactions (
    customer_id,
    merchant_id,
    transaction_type,
    amount,
    commission_percentage,
    commission_amount,
    transaction_date
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    NOW()
)
`

type CreateTransactionParams struct {
	CustomerID           int32                       `json:"customer_id"`
	MerchantID           sql.NullInt32               `json:"merchant_id"`
	TransactionType      TransactionsTransactionType `json:"transaction_type"`
	Amount               string                      `json:"amount"`
	CommissionPercentage sql.NullString              `json:"commission_percentage"`
	CommissionAmount     sql.NullString              `json:"commission_amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransaction,
		arg.CustomerID,
		arg.MerchantID,
		arg.TransactionType,
		arg.Amount,
		arg.CommissionPercentage,
		arg.CommissionAmount,
	)
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT id, customer_id, merchant_id, transaction_type, amount, commission_percentage, commission_amount, transaction_date
FROM transactions
`

func (q *Queries) GetAllTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.MerchantID,
			&i.TransactionType,
			&i.Amount,
			&i.CommissionPercentage,
			&i.CommissionAmount,
			&i.TransactionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByCustomerID = `-- name: GetTransactionsByCustomerID :many
SELECT id, customer_id, merchant_id, transaction_type, amount, commission_percentage, commission_amount, transaction_date
FROM transactions
WHERE customer_id = ?
ORDER BY transaction_date DESC
`

func (q *Queries) GetTransactionsByCustomerID(ctx context.Context, customerID int32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.MerchantID,
			&i.TransactionType,
			&i.Amount,
			&i.CommissionPercentage,
			&i.CommissionAmount,
			&i.TransactionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByMerchantID = `-- name: GetTransactionsByMerchantID :many
SELECT id, customer_id, merchant_id, transaction_type, amount, commission_percentage, commission_amount, transaction_date
FROM transactions
WHERE merchant_id = ?
ORDER BY transaction_date DESC
`

func (q *Queries) GetTransactionsByMerchantID(ctx context.Context, merchantID sql.NullInt32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByMerchantID, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.MerchantID,
			&i.TransactionType,
			&i.Amount,
			&i.CommissionPercentage,
			&i.CommissionAmount,
			&i.TransactionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
