// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createEmployee = `-- name: CreateEmployee :execresult
INSERT INTO employees (
    name,
    email,
    age,
    department
)
VALUES (?, ?, ?, ?)
`

type CreateEmployeeParams struct {
	Name       string
	Email      string
	Age        int32
	Department string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEmployee,
		arg.Name,
		arg.Email,
		arg.Age,
		arg.Department,
	)
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE id = ?
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmployee, id)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, name, email, age, department, created_at, updated_at
FROM employees
WHERE id = ?
`

func (q *Queries) GetEmployee(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Age,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployees = `-- name: GetEmployees :many
SELECT id, name, email, age, department, created_at, updated_at
FROM employees
`

func (q *Queries) GetEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, getEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Age,
			&i.Department,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :exec
UPDATE employees
SET
    name = ?,
    email = ?,
    age = ?,
    department = ?
WHERE id = ?
`

type UpdateEmployeeParams struct {
	Name       string
	Email      string
	Age        int32
	Department string
	ID         int64
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployee,
		arg.Name,
		arg.Email,
		arg.Age,
		arg.Department,
		arg.ID,
	)
	return err
}
