// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Employee struct {
	ID         int64
	Name       string
	Email      string
	Age        int32
	Department string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
