apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: paylater
spec:
  selector:
    app: admin

  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091

  type: ClusterIP